<a href="https://colab.research.google.com/github/Kammarianand/Java-Threading/blob/main/KNN_supervise_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p>knn_supervise algorithm classification</p>

In [68]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

In [69]:
data = pd.read_csv("demo.csv")

In [70]:
data

Name  Age     Sport  Gender
0    chandu   32  football       1
1      Mark   40   Nothing       1
2      Sara   16   cricket       0
3     Zaira   34   cricket       0
4    Sachin   55   Nothing       1
5     Rahul   40   cricket       1
6     Pooja   20   Nothing       0
7     Smith   15   cricket       1
8   Lakshmi   55  football       0
9   Michael   15  football       1

In [71]:
sport = pd.get_dummies(data["Sport"],drop_first=True)


In [72]:
sport

cricket  football
0        0         1
1        0         0
2        1         0
3        1         0
4        0         0
5        1         0
6        0         0
7        1         0
8        0         1
9        0         1

In [73]:
data.pop("Sport")

0    football
1     Nothing
2     cricket
3     cricket
4     Nothing
5     cricket
6     Nothing
7     cricket
8    football
9    football
Name: Sport, dtype: object

In [ ]:
data

Name  Age  Gender
0    chandu   32       1
1      Mark   40       1
2      Sara   16       0
3     Zaira   34       0
4    Sachin   55       1
5     Rahul   40       1
6     Pooja   20       0
7     Smith   15       1
8   Lakshmi   55       0
9   Michael   15       1

In [ ]:
fdata = pd.concat([data,sport],axis=1)

In [ ]:
fdata

Name  Age  Gender  cricket  football
0    chandu   32       1        0         1
1      Mark   40       1        0         0
2      Sara   16       0        1         0
3     Zaira   34       0        1         0
4    Sachin   55       1        0         0
5     Rahul   40       1        1         0
6     Pooja   20       0        0         0
7     Smith   15       1        1         0
8   Lakshmi   55       0        0         1
9   Michael   15       1        0         1

In [ ]:
X = fdata.iloc[:,[1,2]]
y = fdata.iloc[:,[3,4]]

In [67]:
print(X)
print(y)

   Age  Gender
0   32       1
1   40       1
2   16       0
3   34       0
4   55       1
5   40       1
6   20       0
7   15       1
8   55       0
9   15       1
   cricket  football
0        0         1
1        0         0
2        1         0
3        1         0
4        0         0
5        1         0
6        0         0
7        1         0
8        0         1
9        0         1


In [ ]:
python = KNeighborsClassifier(n_neighbors=3)
python.fit(X,y)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
python.predict([[20,1]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  "X does not have valid feature names, but"


array([[1, 0]], dtype=uint8)

In [ ]:
python.predict([[20,0]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  "X does not have valid feature names, but"


array([[1, 0]], dtype=uint8)

In [65]:
python.predict([[55,0]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  "X does not have valid feature names, but"


array([[0, 0]], dtype=uint8)

In [74]:
from sklearn.svm import SVC

In [75]:
colab = SVC()

In [78]:
data = pd.read_csv("demo.csv")

In [81]:
data["Sport"].replace(["football","Nothing","cricket"],[0,1,2],inplace=True)

In [83]:
data.columns

Index(['Name', 'Age', 'Sport', 'Gender'], dtype='object')

In [86]:
colab.fit(data.iloc[:,[1,3]],data['Sport'])

SVC()

In [87]:
colab.predict([[20,1]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  "X does not have valid feature names, but"


array([2])